### ISSUE TITLE
time to match new git and node syntax

### ISSUE THREAD

**Issue by Sonic1paRadise** [YTP-Plus/YTPPlusLauncher#3]
when open it gaves
Error

boot.lua:530: conf.lua:12: attempt to concatenate a nil value

Traceback

[C]: in function 'error'
main.lua:89: in function 'update'
[C]: in function 'xpcall'

and in console
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Error: [string "boot.lua"]:530: conf.lua:12: attempt to concatenate a nil value
stack traceback:
        [string "boot.lua"]:777: in function <[string "boot.lua"]:773>
        [C]: in function 'error'
        [string "boot.lua"]:530: in function 'init'
        main.lua:89: in function 'update'
        [string "boot.lua"]:612: in function <[string "boot.lua"]:594>
        [C]: in function 'xpcall'

**Comment by KiwifruitDev** [comment]
This repository is not supported anymore.
