### ISSUE TITLE
uhh?

### ISSUE THREAD

**Issue by TannerOBJ** [YTP-Plus/YTPPlusLauncher#5]
idk, it just says to copy:
Error

boot.lua:530: conf.lua:12: attempt to concatenate a nil value

Traceback

[C]: in function 'error'
main.lua:89: in function 'update'
[C]: in function 'xpcall'

**Comment by nuppington-bit** [comment]
Run `git clone https://github.com/YTP-Plus/YTPPlusCLI.git` in the launchers directory.

**Comment by KiwifruitDev** [comment]
This repository is not supported anymore.
